fix bad merg when the new deploy_dns was introduced

diff --git a/qubinode-installer b/qubinode-installer
--- a/qubinode-installer
+++ b/qubinode-installer
@@ -269,10 +269,11 @@ function set_openshift_rhsm_pool_id () {
 
     #TODO: this should be change once we start deploy OKD
     if [ "${maintenance}" == "rhsm" ]
-      if [ "A${product_opt}" == "Aocp" ]
+    then
+      if [ "A${cluster_opt}" == "Aocp" ]
       then
           check_for_openshift_subscription
-      elif [ "A${product_opt}" == "Aokd" ]
+      elif [ "A${cluster_opt}" == "Aokd" ]
       then
           echo "OpenShift Subscription not required"
       else
@@ -280,6 +281,7 @@ function set_openshift_rhsm_pool_id () {
         exit 1
       fi
     fi
+
 }
 
 # this function checks if the system is registered to RHSM
@@ -645,8 +647,6 @@ function ask_for_vault_values () {
     encrypt_ansible_vault "${vaultfile}"
 }
 
-
-
 function prereqs () {
     # setup required paths
     setup_required_paths
@@ -759,12 +759,33 @@ function ask_user_input () {
     ask_for_vault_values "${vault_vars_file}"
 }
 
+function check_for_rhel_qcow_image () {
+    # check for required OS qcow image and copy it to right location
+    libvirt_dir=$(awk '/^kvm_host_libvirt_dir/ {print $2}' "${project_dir}/samples/all.yml")
+    os_qcow_image=$(awk '/^os_qcow_image_name/ {print $2}' "${project_dir}/samples/all.yml")
+    if [ ! -f "${libvirt_dir}/${os_qcow_image}" ]
+    then
+        if [ -f "${project_dir}/${os_qcow_image}" ]
+        then
+            sudo cp "${project_dir}/${os_qcow_image}" "${libvirt_dir}/${os_qcow_image}"
+        else
+            echo "Could not find ${project_dir}/${os_qcow_image}, please download the ${os_qcow_image} to ${project_dir}."
+            echo "Please refer the documentation for additional information."
+            exit 1
+        fi
+    else
+        echo "The require OS image ${libvirt_dir}/${os_qcow_image} was found."
+    fi
+}
+
 function installer_preflight () {
     setup_sudoers
     setup_user_ssh_key
     setup_variables
     ask_user_input
+    check_for_rhel_qcow_image
 
+    # Setup admin user variable
     if grep '""' "${vars_file}"|grep -q admin_user
     then
         echo "Updating ${vars_file} admin_user variable"
@@ -774,6 +795,7 @@ function installer_preflight () {
 
 function setup_kvm_host () {
     prereqs
+    # check for host inventory file
     if [ ! -f "${hosts_inventory_dir}/hosts" ]
     then
         echo "Inventory file ${hosts_inventory_dir}/hosts is missing"
@@ -782,6 +804,7 @@ function setup_kvm_host () {
         exit 1
     fi
 
+    # check for inventory directory
     if [ -f "${vars_file}" ]
     then
         if grep '""' "${vars_file}"|grep -q inventory_dir
@@ -798,10 +821,18 @@ function setup_kvm_host () {
         exit 1
      fi
 
-     if [ ! -f /usr/bin/ansible ]
+    # Check for ansible and ansible role
+    ROLE_PRESENT=$(ansible-galaxy list | grep 'swygue.edge_host_setup')
+    if [ ! -f /usr/bin/ansible ]
     then
         echo "Ansible is not installed"
         echo "Please run qubinode-installer -m ansible"
+        echo ""
+        exit 1
+    elif [ "A${ROLE_PRESENT}" == "A" ]
+    then
+        echo "Required role swygue.edge_host_setup is missing."
+        echo "Please run run qubinode-installer -m ansible"
         echo ""
         exit 1
     fi
@@ -893,42 +924,39 @@ function qubinode_vm_manager () {
        echo "Please run qubinode-installer -m ansible"
        echo ""
        exit 1
-    elif [ "A${ROLE_PRESENT}" == "A" ]
-    then
-        echo "Required role swygue.edge_host_setup is missing."
-        echo "Please run run qubinode-installer -m ansible"
-        echo ""
-        exit 1
-    fi
+   elif [ "A${ROLE_PRESENT}" == "A" ]
+   then
+       echo "Required role ansible-role-rhel7-kvm-cloud-init is missing."
+       echo "Please run run qubinode-installer -m ansible"
+       echo ""
+       exit 1
+   fi
+
+   # Check for required Qcow image
+   check_for_rhel_qcow_image
 
    if [ "A${deploy_vm_opt}" == "Adeploy_dns" ]
    then
-#       if grep dns_teardown_dns "${vars_file}"|grep -q true
-#       then
-#           sed -i "s/^dns_teardown_dns: true/dns_teardown_dns: false/g" "${vars_file}"
-#       fi
        ansible-playbook "${project_dir}/playbooks/deploy-dns-server.yml" || exit $?
-       ansible-playbook "${project_dir}/playbooks/idm_server.yml" || exit $?
    elif [ "A${deploy_vm_opt}" == "Adeploy" ]
    then
-       if grep vm_teardown "${vars_file}"|grep -q true
-       then
-           sed -i "s/^vm_teardown: true/vm_teardown: false/g" "${vars_file}"
-       fi
        ansible-playbook "${project_dir}/playbooks/deploy_vms.yml" || exit $?
-    elif [ "A${deploy_vm_opt}" == "Aundeploy" ]
-    then
-#        if grep vm_teardown "${vars_file}"|grep -q false
-#        then
-#            sed -i "s/^vm_teardown: false/vm_teardown: true/g" "${vars_file}"
-#        fi
-        ansible-playbook "${project_dir}/playbooks/deploy_vms.yml" --extra-vars "vm_teardown=true" || exit $?
-    elif [ "A${deploy_vm_opt}" == "Askip" ]
-    then
-        echo "Skipping running ${project_dir}/playbooks/deploy_vms.yml" || exit $?
-    else
+   elif [ "A${deploy_vm_opt}" == "Aundeploy" ]
+   then
+       ansible-playbook "${project_dir}/playbooks/deploy_vms.yml" --extra-vars "vm_teardown=true" || exit $?
+   elif [ "A${deploy_vm_opt}" == "Askip" ]
+   then
+       echo "Skipping running ${project_dir}/playbooks/deploy_vms.yml" || exit $?
+   else
         display_help
-    fi
+   fi
+}
+
+function display_idmsrv_unavailable () {
+        echo "The IdM server variable is not set."
+        echo "This is the ip address of the IdM server."
+        echo "Ensire the IdM server is running, update the variable and try again."
+        exit 1
 }
 
 function qubi_dns_manager () {
@@ -950,16 +978,28 @@ function qubi_dns_manager () {
         exit 1
     fi
 
+    # Make sure IdM server is available
+    IDM_SRV_IP=$(awk -F: '/idm_public_ip/ {print $2}' playbooks/vars/all.yml |grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
+    if [ "A${IDM_SRV_IP}" == "A" ]
+    then
+        display_idmsrv_unavailable
+    elif [ "A${IDM_SRV_IP}" != "A" ]
+    then
+        if ping -c "${IDM_SRV_IP}" &> /dev/null
+        then
+            echo "IdM server is appears to be up"
+        else
+            display_idmsrv_unavailable
+        fi
+    fi
+    
     # Deploy IDM server
-#    if [ "A${option}" == "Aserver" ]
-#    then
-#        SRV_IP=$(awk -F'=' '/dns01/ {print $2}' "${project_dir}/inventory/hosts"|awk '{print $1}' |sed 's/[[:blank:]]//g')
-#        #sed -i "s/idm_public_ip: \"\"/idm_public_ip: "$SRV_IP"/g" "${vars_file}"
-#        echo "Updating idm_public_ip to $SRV_IP"
-#        #sed -i "s/^idm_public_ip:.*\"\"/idm_public_ip: "$SRV_IP"/g" "${vars_file}"
-#        sed -i "s/^idm_public_ip:.*/idm_public_ip: "$SRV_IP"/g" "${vars_file}"
-#        echo "Configuring DNS server"
-#        ansible-playbook "${project_dir}/playbooks/idm_server.yml" || exit $?
+    if [ "A${option}" == "Aserver" ]
+    then
+        ansible-playbook "${project_dir}/playbooks/idm_server.yml" || exit $?
+    fi
+
+    # Add DNS records to IdM
     if [ "A${option}" == "Arecords" ]
     then
         ansible-playbook "${project_dir}/playbooks/add-idm-records.yml" || exit $?
@@ -1018,18 +1058,13 @@ do
         h) display_help
            exit 1
            ;;
-        m) check_args
-           maintenance=$OPTARG
+        m) check_args;
+           maintenance=$OPTARG;
            ;;
         k) check_args;
            check=true
            kvm_host=true
            kvm_host_opt=$OPTARG
-           ;;
-        c) check_args;
-           check=true
-           cluster=true
-           cluster_opt=$OPTARG
            ;;
         d) check_args;
            check=true
@@ -1045,6 +1080,11 @@ do
            check=true
            product=true
            product_opt=$OPTARG
+           ;;
+        c) check_args
+           check=true
+           cluster=true
+           cluster_opt=$OPTARG
            ;;
        --) shift; break;;
        -*) echo Unrecognized flag : "$1" >&2
@@ -1088,21 +1128,41 @@ else
             rhsm_register
         elif [ "${maintenance}" == "ansible" ]
         then
+            #setup_sudoers
+            #setup_variables
+            #ask_user_input
+            #rhsm_register
             setup_ansible
         elif [ "${maintenance}" == "host" ]
         then
+            #setup_sudoers
+            #setup_variables
+            #rhsm_register
+            #setup_ansible
             setup_kvm_host
         elif [ "${maintenance}" == "deploy_dns" ]
         then
             qubinode_vm_manager deploy_dns
+            qubi_dns_manager server
         elif [ "${maintenance}" == "deploy" ]
         then
+            #setup_sudoers
+            #setup_variables
+            #rhsm_register
+            #setup_ansible "${vault_vars_file}"
+            #setup_kvm_host
             qubinode_vm_manager deploy
         elif [ "${maintenance}" == "undeploy" ]
         then
             qubinode_vm_manager undeploy
         elif [ "${maintenance}" == "dns" ]
         then
+            #setup_sudoers
+            #setup_variables
+            #rhsm_register
+            #setup_ansible "${vault_vars_file}"
+            #setup_kvm_host
+            #qubinode_vm_manager deploy
             qubi_dns_manager server
             qubi_dns_manager records
         elif [ "${maintenance}" == "dns" ]
