add check for ansible-role-rhel7-kvm-cloud-init role

diff --git a/qubinode-installer b/qubinode-installer
--- a/qubinode-installer
+++ b/qubinode-installer
@@ -862,6 +862,8 @@ function qubinode_vm_manager () {
    # Deploy VMS
    prereqs
    deploy_vm_opt="$1"
+
+   # Ensure the setup function as was executed
    if [ ! -f "${vars_file}" ]
    then
        echo "${vars_file} is missing"
@@ -869,13 +871,23 @@ function qubinode_vm_manager () {
        echo ""
        exit 1
    fi
+
+   # Ensure the ansible function has bee executed
+   ROLE_PRESENT=$(ansible-galaxy list | grep 'ansible-role-rhel7-kvm-cloud-init')
    if [ ! -f /usr/bin/ansible ]
    then
        echo "Ansible is not installed"
        echo "Please run qubinode-installer -m ansible"
        echo ""
        exit 1
+   elif [ "A${ROLE_PRESENT}" == "A" ]
+   then
+       echo "Required role ansible-role-rhel7-kvm-cloud-init is missing."
+       echo "Please run run qubinode-installer -m ansible"
+       echo ""
+       exit 1
    fi
+
    if [ "A${deploy_vm_opt}" == "Adeploy_dns" ]
    then
        if grep dns_teardown_dns "${vars_file}"|grep -q true
