commented out qubinode_vm_manager

diff --git a/qubinode-installer-working b/qubinode-installer-working
--- a/qubinode-installer-working
+++ b/qubinode-installer-working
@@ -67,79 +67,79 @@ function qubinode_installer_preflight () {
     domain=$(awk '/^domain:/ {print $2}' "${project_dir}/playbooks/vars/all.yml")
 }
 
-function qubinode_vm_manager () {
-   # Deploy VMS
-   prereqs
-   deploy_vm_opt="$1"
-
-   if [ "A${teardown}" != "Atrue" ]
-   then
-       # Ensure the setup function as was executed
-       if [ ! -f "${vars_file}" ]
-       then
-           qubinode_installer_preflight
-           #echo "${vars_file} is missing"
-           #echo "Please run qubinode-installer -m setup"
-           #echo ""
-           #exit 1
-       fi
-
-       # Ensure the ansible function has bee executed
-      # Check for ansible and ansible role
-       if [ -f /usr/bin/ansible ]
-       then
-           ROLE_PRESENT=$(ansible-galaxy list | grep 'swygue.edge_host_setup')
-           if [ "A${ROLE_PRESENT}" == "A" ]
-           then
-               qubinode_setup_ansible
-           fi
-       else
-           qubinode_setup_ansible
-       fi
-
-
-       # Check for required Qcow image
-       check_for_rhel_qcow_image
-    fi
-
-   DNS_PLAY="${project_dir}/playbooks/deploy-dns-server.yml"
-   NODES_PLAY="${project_dir}/playbooks/deploy_nodes.yml"
-   NODES_POST_PLAY="${project_dir}/playbooks/nodes_post_deployment.yml"
-   CHECK_OCP_INVENTORY="${project_dir}/inventory/inventory.3.11.rhel.gluster"
-   NODES_DNS_RECORDS="${project_dir}/playbooks/nodes_dns_records.yml"
-
-   if [ "A${deploy_vm_opt}" == "Adeploy_dns" ]
-   then
-       if [ "A${teardown}" == "Atrue" ]
-       then
-           echo "Remove DNS VM"
-           ansible-playbook "${DNS_PLAY}" --extra-vars "vm_teardown=true" || exit $?
-       else
-           echo "Deploy DNS VM"
-           ansible-playbook "${DNS_PLAY}" || exit $?
-       fi
-   elif [ "A${deploy_vm_opt}" == "Adeploy_nodes" ]
-   then
-       if [ "A${teardown}" == "Atrue" ]
-       then
-           echo "Remove ${qubinode_product} VMs"
-           ansible-playbook "${NODES_DNS_RECORDS}" --extra-vars "vm_teardown=true" || exit $?
-           ansible-playbook "${NODES_PLAY}" --extra-vars "vm_teardown=true" || exit $?
-           if [[ -f ${CHECK_OCP_INVENTORY}  ]]; then
-              rm -rf ${CHECK_OCP_INVENTORY}
-           fi
-       else
-           echo "Deploy ${qubinode_product} VMs"
-           ansible-playbook "${NODES_PLAY}" || exit $?
-           ansible-playbook "${NODES_POST_PLAY}" || exit $?
-       fi
-   elif [ "A${deploy_vm_opt}" == "Askip" ]
-   then
-       echo "Skipping running ${project_dir}/playbooks/deploy_vms.yml" || exit $?
-   else
-        display_help
-   fi
-}
+#function qubinode_vm_manager () {
+#   # Deploy VMS
+#   prereqs
+#   deploy_vm_opt="$1"
+#
+#   if [ "A${teardown}" != "Atrue" ]
+#   then
+#       # Ensure the setup function as was executed
+#       if [ ! -f "${vars_file}" ]
+#       then
+#           qubinode_installer_preflight
+#           #echo "${vars_file} is missing"
+#           #echo "Please run qubinode-installer -m setup"
+#           #echo ""
+#           #exit 1
+#       fi
+#
+#       # Ensure the ansible function has bee executed
+#      # Check for ansible and ansible role
+#       if [ -f /usr/bin/ansible ]
+#       then
+#           ROLE_PRESENT=$(ansible-galaxy list | grep 'swygue.edge_host_setup')
+#           if [ "A${ROLE_PRESENT}" == "A" ]
+#           then
+#               qubinode_setup_ansible
+#           fi
+#       else
+#           qubinode_setup_ansible
+#       fi
+#
+#
+#       # Check for required Qcow image
+#       check_for_rhel_qcow_image
+#    fi
+#
+#   DNS_PLAY="${project_dir}/playbooks/deploy-dns-server.yml"
+#   NODES_PLAY="${project_dir}/playbooks/deploy_nodes.yml"
+#   NODES_POST_PLAY="${project_dir}/playbooks/nodes_post_deployment.yml"
+#   CHECK_OCP_INVENTORY="${project_dir}/inventory/inventory.3.11.rhel.gluster"
+#   NODES_DNS_RECORDS="${project_dir}/playbooks/nodes_dns_records.yml"
+#
+#   if [ "A${deploy_vm_opt}" == "Adeploy_dns" ]
+#   then
+#       if [ "A${teardown}" == "Atrue" ]
+#       then
+#           echo "Remove DNS VM"
+#           ansible-playbook "${DNS_PLAY}" --extra-vars "vm_teardown=true" || exit $?
+#       else
+#           echo "Deploy DNS VM"
+#           ansible-playbook "${DNS_PLAY}" || exit $?
+#       fi
+#   elif [ "A${deploy_vm_opt}" == "Adeploy_nodes" ]
+#   then
+#       if [ "A${teardown}" == "Atrue" ]
+#       then
+#           echo "Remove ${qubinode_product} VMs"
+#           ansible-playbook "${NODES_DNS_RECORDS}" --extra-vars "vm_teardown=true" || exit $?
+#           ansible-playbook "${NODES_PLAY}" --extra-vars "vm_teardown=true" || exit $?
+#           if [[ -f ${CHECK_OCP_INVENTORY}  ]]; then
+#              rm -rf ${CHECK_OCP_INVENTORY}
+#           fi
+#       else
+#           echo "Deploy ${qubinode_product} VMs"
+#           ansible-playbook "${NODES_PLAY}" || exit $?
+#           ansible-playbook "${NODES_POST_PLAY}" || exit $?
+#       fi
+#   elif [ "A${deploy_vm_opt}" == "Askip" ]
+#   then
+#       echo "Skipping running ${project_dir}/playbooks/deploy_vms.yml" || exit $?
+#   else
+#        display_help
+#   fi
+#}
 
 function qubinode_vm_deployment_precheck () {
    # This function ensure that the host is setup as a KVM host.
